CREATE TABLE "movies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_on" timestamp NOT NULL DEFAULT (now()),
  "modified_on" timestamp,
  "title" varchar(255) NOT NULL,
  "description" text NOT NULL,
  "duration" int NOT NULL,
  "artists" json NOT NULL,
  "genres" json NOT NULL,
  "file" varchar(255) NOT NULL,
);